---
# tasks file for mariadbroles
- name: "creating a group"
  group: name=grp1 state=present

- name: Creating a user
  user: name={{item}} state=present group=grp1
  with_items:
     - user1
     - user2

